systems:
  all:
    hosts:
      tr-mng:
        ansible_host: 192.168.5.175
        ansible_user: pvinfra
        # Carpeta de destino donde se sincronizarán los archivos del repo
        replication_subdir: "tr-mng"
        replication_dest: "/opt/stacks/tr-mng"
        replication_compose_dir: "/opt/stacks/tr-mng"   # donde está docker-compose.yml
        replication_bind_dir: "/opt/stacks/tr-mng/bind" # carpeta específica para bind

      tr-db:
        ansible_host: 192.168.5.171
        ansible_user: pvinfra
        replication_subdir: "tr-db"
        replication_dest: "/opt/stacks/tr-db"
        replication_compose_dir: "/opt/stacks/tr-db"
        replication_bind_dir: "/opt/stacks/tr-db/bind"

      tr-airflow:
        ansible_host: 192.168.5.172
        ansible_user: pvinfra
        replication_subdir: "tr-airflow"
        replication_dest: "/opt/stacks/tr-airflow"
        replication_compose_dir: "/opt/stacks/tr-airflow"
        replication_bind_dir: "/opt/stacks/tr-airflow/bind"

      tr-spark:
        ansible_host: 192.168.5.173
        ansible_user: pvinfra
        replication_subdir: "tr-spark"
        replication_dest: "/opt/stacks/tr-spark"
        replication_compose_dir: "/opt/stacks/tr-spark"
        replication_bind_dir: "/opt/stacks/tr-spark/bind"

      tr-kafka:
        ansible_host: 192.168.5.174
        ansible_user: pvinfra
        replication_subdir: "tr-kafka"
        replication_dest: "/opt/stacks/tr-kafka"
        replication_compose_dir: "/opt/stacks/tr-kafka"
        replication_bind_dir: "/opt/stacks/tr-kafka/bind"

      localhost:
        ansible_connection: local

    children:
      # Hosts donde gestionamos Docker
      docker_hosts:
        hosts:
          tr-mng:
          tr-db:
          tr-airflow:
          tr-spark:
          tr-kafka:

      # Nodo donde corre Portainer Server (equivalente al antiguo pv-infra-master)
      portainer_server:
        hosts:
          tr-mng:

      # Nodos donde corren Portainer Agent
      portainer_agents:
        hosts:
          tr-db:
          tr-airflow:
          tr-spark:
          tr-kafka:

      # Grupo usado para el play 20 (vCenter)
      vcenter:
        hosts:
          localhost: